# Library paths: Uncomment as required:
#####################
#INCLUDEPATH=/home/user/include
#LIBPATH=/home/user/lib

CC=mpic++
CFLAGS=-c -g -Wall -fopenmp
LDFLAGS=-fopenmp -lgsl -lgslcblas
SOURCES=mainSerial.cpp mainMPI.cpp PEG.cpp PESolver.cpp PEMainSupport.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) pegSerial pegMPI

pegSerial: mainSerial.o PEMainSupport.o PEG.o PESolver.o via.o
	$(CC) $(LDFLAGS) mainSerial.o PEMainSupport.o PEG.o PESolver.o -o ../$@

pegMPI: mainMPI.o PEMainSupport.o PEG.o PESolver.o via.o
	$(CC) $(LDFLAGS) mainMPI.o PEMainSupport.o PEG.o PESolver.o -o ../$@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

install: pegSerial pegMPI installDirs
	cp ../pegSerial "${PREFIX}"/bin/pegSerial
	cp ../pegMPI "${PREFIX}"/bin/pegMPI
# 	cp -r ../materialDatabase "${PREFIX}"/bin/peg.d/materialDatabase
	cp -r ../materialDatabase "${PREFIX}"/local/peg/materialDatabase

installDirs:
	mkdir -p "${PREFIX}"/bin
	mkdir -p "${PREFIX}"/local/peg
